project: &project "aesthetic_destinations"

create: 20
background_dir: "data/{}/background"
topic: "Body skin care for women"
language: "Hungarian friendly tone"
caption_style: "science fun fact quotes"
social_media: "Instagram"

avoid_prompt: >
  Do not write false informations
  Do not use emojis or hastags!.
  Do not leave empty spaces between each line
  Do not exceed the request number

example: >
  "I don’t have the luxury of time to be unhappy. I have too much to do. I have too much do accomplish. Who has the time to be unhappy?. \n"
  "Time flies. It’s up to you to be the navigator. \n"
  "We wander for distraction, but we travel for fulfillment. \n"
  "Living on Earth is expensive, but it does include a free trip around the sun every year. \n"
  "It is a luxury to be understood. \n"
  "It is the ultimate luxury to combine passion and contribution. It’s also a clear path to happiness. \n"
  "Art is not a luxury, but a necessity. \n"

line_text: "multiline"
sep: "\n"

font:
  font_type: "MONTSERRAT-REGULAR.TTF"
  text_color: "#0000"
  font_size: 30
  wrap_block: 50

  text_coords:
    auto: False
    width: 150 #if auto is False
    height: 400 #if auto is False
    align: "center"

path:
  path_to_image: "./data/{}/background/{}_template_{}.png"
  path_to_font: "./fonts/"
  path_to_video: "data/{}/videos"

image_processing:
  alpha_overlay: 0.01
  color_overlay: "#0000"
  color_portrait: "#FFFFFF"

video_processing:
  frame_rate: 15
  video_duration: 10
  images_in_video: 10
  width_resize: 800
