avoid_prompt: >
  Do not write false informations
  Do not use emojis or hastags!.
  Do not leave empty spaces between each line
  Do not exceed the request number

example: >
  "Each strand of hair can contain traces of 14 different elements (including gold) \n"
  "Hair absorbs oil out of the water, working as a natural sponge! \n"
  "On average, Redheads have the lowest amount of hair stands (86,000). \n"
  "Hair is composed of the following elements: Carbon (50%), Oxygen (21%) Nitrogen (17%), Hydrogen (6%), Sulphur (5%). \n"
  "The longest female hair was measured at 18 feet and 5.5 inches. Xie Jiuping grew her hair for over 30 years! \n"

line_text: "multiline"
sep: "\n"

font:
  font_type: "MONTSERRAT-REGULAR.TTF"
  text_color: "#0000"
  font_size: 30
  wrap_block: 50

  text_coords:
    auto: False
    width: 180 #if auto is False
    height: 500 #if auto is False
    align: "left"

path:
  path_to_image: "src/data/{}/background/{}_template_{}.png"
  path_to_font: "src/fonts/"
  path_to_video: "src/data/{}/videos"

image_processing:
  alpha_overlay: 0.01
  color_overlay: "#0000"
  color_portrait: "#FFFFFF"

video_processing:
  frame_rate: 15
  video_duration: 10
  images_in_video: 10
  width_resize: 800
