project: aesthetic_destinations

image_processing:
  alpha_overlay: 0.01
  color_overlay: "#0000"
  color_portrait: "#0000"

blogger:
  blog:
    topic: "Dubai"
    tone: "professional and concise"
    aspects:
      - - Suites in Dubai
        - https://www.anantara.com/en/downtown-dubai/rooms/anantara-burj-khalifa-view-suite
      - - Burj Khalifa
        - https://www.anantara.com/en/downtown-dubai/rooms/deluxe-burj-khalifa-view-room

    images_path: "{}/images/"
    template_file_path: "{}/templates/blog_template.html"
    output_file_path: "{}/tables/blog.html"

    extra_promo_links:
      - href: "https://example-link3.com"
        text: "Check out our special offer!"
      - href: "https://example-link4.com"
        text: "Discover more here!"

    prompts:
      generate_keywords: |
        Write 5 SEO keywords for a blog post about {}.

      incorporate_keywords: |
        Rewrite the following text to naturally include these keywords about {}: {}.

      generate_title: |
        Create a one line very short and engaging blog post title about {}.

      generate_subtitle: |
        Create a one line very short and interesting subtitle for a section of a blog post about {}, specifically focusing on {}.

      generate_introduction: |
        Write a one line short introduction for a blog post about {}. Write at most 4 lines.

      generate_link_text: |
        Create a short, engaging call-to-action link text related to '{}'.
        Example of output
        Deluxe Burji Khalifa Room

      generate_promo_context: |
        Write a 10 max word friendly and informative paragraph that provides value to the reader and naturally introduces a promotional link related to '{}'.

      generate_section: |
        Write a short detailed section for a blog post about {} focusing on '{}'. 
        You have a mandatory limit of 100 words of output text, it must be very short.
        If there are links you should not remove them.
        Do not say welcome and do not introduce yourself.
        Do not make introduction and get to the point.

      generate_ending: |
        Write a compelling ending statement for a blog post about {} that includes a call to action for readers.

  hmtl_template: |

    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{ title }}</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
        <style>
          #blog {
            background: snow;
            font-family: "Montserrat", sans-serif;
            text-align: justify;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            padding: 5%;
          }

          h2 {
            text-align: center;
            font-size: 1.5em;
          }

          h4 {
            text-align: center;
            font-size: 1.2em;
          }

          p {
            font-size: 0.9em;
          }

          .promolink {
            background-color: #e0e0e0;
            color: #333333;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            padding: 2%;
            font-weight: bold;
            margin: 10px 0;
            display: inline-block;
            transition: transform 0.3s, background-color 0.3s, color 0.3s;
          }

          .promolink:hover {
            transform: scale(1.1);
            background-color: #cfb53b;
            color: #ffffff;
          }
        </style>
      </head>
      <body>
        <div id="blog">
          <section>
            <h2>{{ title }}</h2>
            <p>{{ introduction }}</p>
            {% if cover.image_url %}
            <img src="{{ cover.image_url }}" alt="cover" />
            {% endif %}
          </section>
          {% for section in sections %}
          <section>
            <h4>{{ section.header }}</h4>
            {% if section.image_url %}
            <img src="{{ section.image_url }}" alt="{{ section.header }}" />
            {% endif %} {% for paragraph in section.paragraphs %}
            <p>{{ paragraph }}</p>
            {% endfor %} {% if section.promo %}
            <div>
              <a href="{{ section.promo.link }}" class="promolink">
                {{ section.promo.link_text }}
              </a>
            </div>
            {% endif %}
          </section>
          {% endfor %}
          <div>
            <h2>Conclusion</h2>
            <p>{{ ending.content }}</p>
            {% if ending.promo_links %}
            <div>
              <h4>Promotions and Rooms</h4>
              <ul>
                {% for promo_link in ending.promo_links %}
                <li>
                  <a href="{{ promo_link.href }}" class="promolink">
                    {{ promo_link.text }}
                  </a>
                </li>
                {% endfor %}
              </ul>
            </div>
            {% endif %}
          </div>
        </div>
      </body>
    </html>

anantara:
  destinations:
    Africa:
      Mauritius:
        - "Iko Mauritius Resort"
      Mozambique:
        - "Bazaruto Island Resort"
        - "Medjumbe Island Resort"
      Tunisia:
        - "Sahara Tozeur Resort"
      Zambia:
        - "Royal Livingstone Hotel"

    Asia:
      Cambodia:
        - "Angkor Resort"
      China:
        - "Guiyang Resort"
        - "Xishuangbanna Resort"
      Indonesia:
        - "Seminyak Resort"
        - "Uluwatu Resort"
        - "Bali Vacation Club"
      Malaysia:
        - "Desaru Coast Resort"
      Maldives:
        - "Dhigu Resort"
        - "Kihavah Villas"
        - "Naladhu Private Island"
        - "Veli Resort"
        - "Niyama Private Islands"
      Oman:
        - "Al Baleed Resort Salalah"
        - "Al Jabal Al Akhdar Resort"
      Qatar:
        - "Banana Island Resort"
      Sri Lanka:
        - "Kalutara Resort"
        - "Peace Haven Tangalle Resort"
      Thailand:
        Bangkok:
          - "Riverside Resort"
          - "Siam Hotel"
          - "Loy Pela Voyages"
        Chiang Mai:
          - "Chiang Mai Resort"
          - "Chiang Mai Serviced Suites"
        Chiang Rai:
          - "Golden Triangle Resort"
      Vietnam:
        - "Hoi An Resort"
        - "Mui Ne Resort"
        - "Quy Nhon Villas"
        - "The Vietage by Anantara"

    Europe:
      France:
        - "Plaza Nice Hotel"
      Hungary:
        - "New York Palace Budapest Hotel"
      Ireland:
        - "The Marker Dublin"
      Italy:
        - "Convento di Amalfi Hotel"
        - "Palazzo Naiadi Rome Hotel"
      Netherlands:
        - "Grand Hotel Krasnapolsky Amsterdam"
      Portugal:
        - "Vilamoura Resort"
      Spain:
        - "Villa Padierna Palace Resort"

    Middle East:
      United Arab Emirates:
        Abu Dhabi:
          - "Al Yamm Resort"
          - "Al Sahel Resort"
          - "Desert Islands Resort"
          - "Qasr Al Sarab Resort"
          - "Eastern Mangroves Hotel"
        Dubai:
          - "The Palm Resort"
          - "World Islands Resort"
          - "Downtown Dubai Hotel"
        Ras Al Khaimah:
          - "Mina Al Arab Ras Al Khaimah"

    Oceania:
      Seychelles:
        - "Maia Seychelles Villas"
