project: aesthetic_destinations

image_processing:
  alpha_overlay: 0.01
  color_overlay: "#0000"
  color_portrait: "#0000"

blogger:
  blog:
    topic: "Dubai"
    tone: "friendly"
    aspects:
      - - Suites in Dubai
        - https://www.anantara.com/en/downtown-dubai/rooms/anantara-burj-khalifa-view-suite
      - - Burj Khalifa
        - https://www.anantara.com/en/downtown-dubai/rooms/deluxe-burj-khalifa-view-room

    template_file_path: "{}/templates/blog_template.html"
    output_file_path: "{}/tables/blog.html"
    prompts:
      generate_keywords: |
        Write 5 SEO keywords for a blog post about {}.

      incorporate_keywords: |
        Rewrite the following text to naturally include these keywords about {}: {}.

      generate_title: |
        Create a one line very short and engaging blog post title about {}.

      generate_subtitle: |
        Create a one line very short and interesting subtitle for a section of a blog post about {}, specifically focusing on {}.

      generate_introduction: |
        Write a one line short introduction for a blog post about {}. Write at most 4 lines.

      generate_link_text: |
        Create a short, engaging call-to-action link text related to '{}'.
        Example of output
        Deluxe Burji Khalifa Rooms: https://www.anantara.com/en/downtown-dubai/rooms/deluxe-burj-khalifa-view-room,

      generate_promo_context: |
        Write a 10 max word friendly and informative paragraph that provides value to the reader and naturally introduces a promotional link related to '{}'.

      generate_section: |
        Write a short detailed section for a blog post about {} focusing on '{}'. 
        You have a mandatory limit of 100 words of output text, it must be very short.
        If there are links you should not remove them.

      generate_ending: |
        Write a compelling ending statement for a blog post about {} that includes a call to action for readers.

  hmtl_template: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>{{ title }}</title>
    </head>
    <body
      style="
        font-family: 'Georgia', serif;
        margin: 0;
        padding: 0;
        color: #333;
        background-color: #f4f4f4;
      "
    >
      <h2
        style="
          text-align: center;
          font-size: 2em;
          margin: 1em 0;
          color: #2a5d84;
        "
      >
        {{ title }}
      </h2>

      {% for section in sections %}
      <section
        style="
          background-color: white;
          padding: 2em;
          margin-bottom: 1em;
          box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        "
      >
        <h4
          style="
            font-family: 'Arial', sans-serif;
            font-size: 1.5em;
            font-weight: bold;
            color: #2a5d84;
            margin-bottom: 0.5em;
          "
        >
          {{ section.header }}
        </h4>

        {% for paragraph in section.paragraphs %}
        <p
          style="
            font-family: 'Montserrat', sans-serif;
            font-weight: 300;
            text-align: justify;
            line-height: 1.6;
            font-size: 0.9em;
            color: #4a4a4a;
            margin-bottom: 1em;
          "
        >
          {{ paragraph }}
        </p>
        {% endfor %}

        {% if section.promo %}
        <div style="text-align: center; margin-top: 2em; margin-bottom: 2em">
          <a
            href="{{ section.promo.link }}"
            style="margin-left: 1em; margin-right: 1em"
          >
            <img
              border="0"
              src="{{ section.promo.image_url }}"
              alt="{{ section.promo.alt_text }}"
              style="height: auto; max-width: 100%; border-radius: 8px"
            />
          </a>
          <p style="font-size: 1em; font-weight: bold; margin-top: 1em">
            <a
              href="{{ section.promo.link }}"
              style="
                color: #2a5d84;
                text-decoration: none;
                background-color: #eef2f7;
                padding: 0.4em 0.8em;
                border-radius: 4px;
                box-shadow: 0 1px 2px rgba(0, 0, 0, 0.15);
              "
            >
              {{ section.promo.link_text }}
            </a>
          </p>
        </div>
        {% endif %}
      </section>
      {% endfor %}

      <div
        id="conclusion"
        style="
          background-color: white;
          padding: 2em;
          margin-top: 2em;
          box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        "
      >
        <h2
          style="
            font-size: 2em;
            font-weight: bold;
            color: #2a5d84;
            margin-bottom: 0.5em;
          "
        >
          Conclusion
        </h2>
        <p
          style="
            font-family: 'Montserrat', sans-serif;
            font-weight: 300;
            text-align: justify;
            line-height: 1.6;
            font-size: 0.9em;
            color: #4a4a4a;
          "
        >
          {{ ending.content }}
        </p>

        {% if ending.promo_links %}
        <div class="promo-links" style="margin-top: 2em">
          <h4
            style="
              font-size: 1.5em;
              font-weight: bold;
              color: #2a5d84;
              margin-bottom: 0.5em;
            "
          >
            Promotions and Rooms
          </h4>
          <ul style="list-style: none; padding: 0">
            {% for promo_link in ending.promo_links %}
            <li style="margin-bottom: 1em">
              <a
                href="{{ promo_link.href }}"
                style="
                  color: #2a5d84;
                  text-decoration: none;
                  background-color: #eef2f7;
                  padding: 0.4em 0.8em;
                  border-radius: 4px;
                  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.15);
                  font-size: 1em;
                "
              >
                {{ promo_link.text }}
              </a>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
    </body>
    </html>

anantara:
  destinations:
    Africa:
      Mauritius:
        - "Iko Mauritius Resort"
      Mozambique:
        - "Bazaruto Island Resort"
        - "Medjumbe Island Resort"
      Tunisia:
        - "Sahara Tozeur Resort"
      Zambia:
        - "Royal Livingstone Hotel"

    Asia:
      Cambodia:
        - "Angkor Resort"
      China:
        - "Guiyang Resort"
        - "Xishuangbanna Resort"
      Indonesia:
        - "Seminyak Resort"
        - "Uluwatu Resort"
        - "Bali Vacation Club"
      Malaysia:
        - "Desaru Coast Resort"
      Maldives:
        - "Dhigu Resort"
        - "Kihavah Villas"
        - "Naladhu Private Island"
        - "Veli Resort"
        - "Niyama Private Islands"
      Oman:
        - "Al Baleed Resort Salalah"
        - "Al Jabal Al Akhdar Resort"
      Qatar:
        - "Banana Island Resort"
      Sri Lanka:
        - "Kalutara Resort"
        - "Peace Haven Tangalle Resort"
      Thailand:
        Bangkok:
          - "Riverside Resort"
          - "Siam Hotel"
          - "Loy Pela Voyages"
        Chiang Mai:
          - "Chiang Mai Resort"
          - "Chiang Mai Serviced Suites"
        Chiang Rai:
          - "Golden Triangle Resort"
      Vietnam:
        - "Hoi An Resort"
        - "Mui Ne Resort"
        - "Quy Nhon Villas"
        - "The Vietage by Anantara"

    Europe:
      France:
        - "Plaza Nice Hotel"
      Hungary:
        - "New York Palace Budapest Hotel"
      Ireland:
        - "The Marker Dublin"
      Italy:
        - "Convento di Amalfi Hotel"
        - "Palazzo Naiadi Rome Hotel"
      Netherlands:
        - "Grand Hotel Krasnapolsky Amsterdam"
      Portugal:
        - "Vilamoura Resort"
      Spain:
        - "Villa Padierna Palace Resort"

    Middle East:
      United Arab Emirates:
        Abu Dhabi:
          - "Al Yamm Resort"
          - "Al Sahel Resort"
          - "Desert Islands Resort"
          - "Qasr Al Sarab Resort"
          - "Eastern Mangroves Hotel"
        Dubai:
          - "The Palm Resort"
          - "World Islands Resort"
          - "Downtown Dubai Hotel"
        Ras Al Khaimah:
          - "Mina Al Arab Ras Al Khaimah"

    Oceania:
      Seychelles:
        - "Maia Seychelles Villas"
