project: aesthetic_destinations

image_processing:
  alpha_overlay: 0.01
  color_overlay: "#0000"
  color_portrait: "#0000"

blogger:
  blog:
    topic: "Dubai"
    tone: "professional travel agency tone"
    aspects:
      - - Suites in Dubai
        - https://www.anantara.com/en/downtown-dubai/rooms/anantara-burj-khalifa-view-suite
      - - Burj Khalifa
        - https://www.anantara.com/en/downtown-dubai/rooms/deluxe-burj-khalifa-view-room

    images_path: "{}/images/"
    template_file_path: "{}/templates/blog_template.html"
    output_file_path: "{}/tables/blog.html"

    extra_promo_links:
      - href: "https://example-link3.com"
        text: "Check out our special offer!"
      - href: "https://example-link4.com"
        text: "Discover more here!"

    prompts:
      generate_keywords: |
        Write 5 SEO keywords for a blog post about {}.

      incorporate_keywords: |
        Rewrite the following text to naturally include these keywords about {}: {}.

      generate_title: |
        Create a one line very short and engaging blog post title about {}.

      generate_subtitle: |
        Create a one line very short and interesting subtitle for a section of a blog post about {}, specifically focusing on {}.

      generate_introduction: |
        Write a one line short introduction for a blog post about {}. Write at most 4 lines.

      generate_link_text: |
        Create a short, engaging call-to-action link text related to '{}'.
        Example of output
        Deluxe Burji Khalifa Room

      generate_promo_context: |
        Write a 10 max word friendly and informative paragraph that provides value to the reader and naturally introduces a promotional link related to '{}'.

      generate_section: |
        Write a short detailed section for a blog post about {} focusing on '{}'. 
        You have a mandatory limit of 100 words of output text, it must be very short.
        If there are links you should not remove them.

      generate_ending: |
        Write a compelling ending statement for a blog post about {} that includes a call to action for readers.

  hmtl_template: |

anantara:
  destinations:
    Africa:
      Mauritius:
        - "Iko Mauritius Resort"
      Mozambique:
        - "Bazaruto Island Resort"
        - "Medjumbe Island Resort"
      Tunisia:
        - "Sahara Tozeur Resort"
      Zambia:
        - "Royal Livingstone Hotel"

    Asia:
      Cambodia:
        - "Angkor Resort"
      China:
        - "Guiyang Resort"
        - "Xishuangbanna Resort"
      Indonesia:
        - "Seminyak Resort"
        - "Uluwatu Resort"
        - "Bali Vacation Club"
      Malaysia:
        - "Desaru Coast Resort"
      Maldives:
        - "Dhigu Resort"
        - "Kihavah Villas"
        - "Naladhu Private Island"
        - "Veli Resort"
        - "Niyama Private Islands"
      Oman:
        - "Al Baleed Resort Salalah"
        - "Al Jabal Al Akhdar Resort"
      Qatar:
        - "Banana Island Resort"
      Sri Lanka:
        - "Kalutara Resort"
        - "Peace Haven Tangalle Resort"
      Thailand:
        Bangkok:
          - "Riverside Resort"
          - "Siam Hotel"
          - "Loy Pela Voyages"
        Chiang Mai:
          - "Chiang Mai Resort"
          - "Chiang Mai Serviced Suites"
        Chiang Rai:
          - "Golden Triangle Resort"
      Vietnam:
        - "Hoi An Resort"
        - "Mui Ne Resort"
        - "Quy Nhon Villas"
        - "The Vietage by Anantara"

    Europe:
      France:
        - "Plaza Nice Hotel"
      Hungary:
        - "New York Palace Budapest Hotel"
      Ireland:
        - "The Marker Dublin"
      Italy:
        - "Convento di Amalfi Hotel"
        - "Palazzo Naiadi Rome Hotel"
      Netherlands:
        - "Grand Hotel Krasnapolsky Amsterdam"
      Portugal:
        - "Vilamoura Resort"
      Spain:
        - "Villa Padierna Palace Resort"

    Middle East:
      United Arab Emirates:
        Abu Dhabi:
          - "Al Yamm Resort"
          - "Al Sahel Resort"
          - "Desert Islands Resort"
          - "Qasr Al Sarab Resort"
          - "Eastern Mangroves Hotel"
        Dubai:
          - "The Palm Resort"
          - "World Islands Resort"
          - "Downtown Dubai Hotel"
        Ras Al Khaimah:
          - "Mina Al Arab Ras Al Khaimah"

    Oceania:
      Seychelles:
        - "Maia Seychelles Villas"
