project: &project "aesthetic_destinations"

create: 5
background_dir: "src/data/{}/background"

topic: "Luxury and Travel"
language: "English friendly tone with basic words"
caption_style: "inspiring quotes"
social_media: "Instagram"
