project: theallurecode

image_processing:
  alpha_overlay: 0.01
  color_overlay: "#0000"
  color_portrait: "#0000"

blogger:
  GOOGLE_BLOGSPOT_ID: 4309253655499790374
  blog:
    topic: "Dubai"
    tone: "using a professional and concise tone"
    aspects:
      - - Why Dubai has the best view suite.
        - https://www.anantara.com/en/downtown-dubai/rooms/anantara-burj-khalifa-view-suite
      - - Burj Khalifa is the best view in town.
        - https://www.anantara.com/en/downtown-dubai/rooms/deluxe-burj-khalifa-view-room

    images_path: "{}/images/"
    template_file_path: "{}/templates/blog_template.html"
    output_file_path: "{}/tables/blog_{}.html"

    extra_promo_links:
      - href: "https://example-link3.com"
        text: "Check out our special offer!"
      - href: "https://example-link4.com"
        text: "Discover more here!"

    prompts:
      system: |
        You are an AI expert in blog content creation. Provide concise, informative, and unique responses in paragraph format. Avoid repetition, off-topic content, overly complex language, and bullet point lists.

      generate_keywords:
        system: |
          Focus on SEO optimization with highly relevant and specific keywords. Avoid generic or irrelevant keywords and listing in bullet points.
        prompt: |
          Generate 5 targeted SEO keywords for a blog post about "{}".

      incorporate_keywords:
        system: |
          Seamlessly integrate keywords into the text in a narrative style. Ensure natural flow and readability. Avoid forced insertions and bullet points.
        prompt: |
          Rewrite this text to include these keywords about "{}": {}.

      generate_title:
        system: |
          Create a captivating, concise title that reflects the blog's theme. Avoid vague, misleading, or list-style titles.
        prompt: |
          Generate an engaging blog post title about "{}".

      generate_subtitle:
        system: |
          Subtitles should add depth, focusing on a specific aspect in a narrative form. Avoid general, broad, or bullet point subtitles.
        prompt: |
          Blog topic: "{}"
          Subtopic: "{}"
          Subtitle:

      generate_introduction:
        system: |
          Write an engaging introduction in paragraph format that sets the tone and provides an overview. Avoid long-winded, off-topic introductions, and bullet points.
        prompt: |
          Write a concise introduction for a blog post about "{}". Limit to 4 lines.

      generate_link_text:
        system: |
          Create engaging, click-enticing link text relevant to the content in a complete sentence. Avoid generic, irrelevant, or list-style link text.
        prompt: |
          Generate a call-to-action link text related to "{}".

      generate_promo_context:
        system: |
          Write a brief, friendly paragraph that leads into a promotional link. Avoid overly salesy content, irrelevance, and bullet point formats.
        prompt: |
          Create a promotional context paragraph related to "{}". Limit to 10 words.

      generate_section:
        system: |
          Develop a detailed, concise section on a specific aspect in paragraph form. Keep under 100 words. Avoid vagueness, straying from the topic, or bullet points, starting the answer with Welcome to or by introducing yourself to the reader.
        prompt: |
          Without Welcoming the reader: Write a detailed section for a blog post about "{}", focusing on "{}".

      generate_ending:
        system: |
          Conclude with a summary and a call to action in a narrative style. Avoid abrupt endings, unrelated content, or bullet point summaries.
        prompt: |
          Write a compelling ending for a blog post about "{}" that encourages reader engagement.
